version: "3.9"
services:
  mareoenvios:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      mysql_db:
        condition: service_healthy
  mysql_db:
    image: "mysql:8.0.28"
    cap_add:
      - SYS_NICE
    restart: always
    ports:
      - 3307:3306
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      MYSQL_DATABASE: db_mareoenvios
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
